# Generated by Django 5.2.18 on 2026-10-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown on the printed plan. A first name or nickname is enough.",
                        max_length=60,
                        verbose_name="first name",
                    ),
                ),
                (
                    "class_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Class 1"),
                            (2, "Class 2"),
                            (3, "Class 3"),
                            (4, "Class 4"),
                        ],
                        verbose_name="class",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "child",
                "verbose_name_plural": "children",
                "ordering": ["name"],
            },
        ),
    ]
